apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleep
  template:
    metadata:
      labels:
        app: ubuntu-sleep
    spec:
      containers:
      - name: ubuntu-container
        image: {{ .Values.image }}
        command: ["sleep", "3600"]  # Sleep for 3600 seconds (1 hour)
